services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: cachedb
      POSTGRES_USER: cache_user
      POSTGRES_PASSWORD: cache_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
